advanced:
  auto_tuning:
    save_best: 5
    trials: 100
  auto_tuning_advanced:
    search_space:
      clustering_sensitivity:
      - 2
      - 15
      topic_granularity:
      - 5
      - 50
  graphs:
    academic_charts: true
    dpi: 300
    figure_height: 8
    figure_width: 12
    formats:
    - pdf
  sota_visuals: true
  system:
    max_memory: auto
    random_seed: 42
    use_gpu: false
ai_labeling:
  enable: false
analysis:
  mode: tune
  save_candidates: true
candidate_parameters:
  candidate_1:
    coherence_score: 0.0
    description: 中等粒度, 平衡聚类, 高稳定性
    min_cluster_size: 31
    min_samples: 1
    min_topic_size: null
    n_components: 10
    n_neighbors: 22
  candidate_2:
    coherence_score: 0.0
    description: 中等粒度, 平衡聚类, 高稳定性
    min_cluster_size: 96
    min_samples: 3
    min_topic_size: null
    n_components: 4
    n_neighbors: 13
  candidate_3:
    coherence_score: 0.0
    description: 中等粒度, 全局聚类, 高稳定性
    min_cluster_size: 123
    min_samples: 5
    min_topic_size: null
    n_components: 3
    n_neighbors: 32
  candidate_4:
    coherence_score: 0.0
    description: 中等粒度, 全局聚类, 高稳定性
    min_cluster_size: 146
    min_samples: 12
    min_topic_size: null
    n_components: 4
    n_neighbors: 35
  candidate_5:
    coherence_score: 0.0
    description: 中等粒度, 平衡聚类, 高稳定性
    min_cluster_size: 86
    min_samples: 3
    min_topic_size: null
    n_components: 4
    n_neighbors: 22
data:
  files:
    social_media: null
    traditional_media: data/(不能删)analyzed_ok3-总库-切分去噪-第二章俄总统数据.xlsx
data_processing:
  text_column: Unit_Text
  metadata_columns:
    - Incident
    - Frame_SolutionRecommendation
    - Frame_ResponsibilityAttribution
    - Frame_CausalExplanation
    - Frame_MoralEvaluation
    - Frame_ProblemDefinition
    - Frame_ActionStatement
    - Valence
    - Evidence_Type
    - Attribution_Level
    - Temporal_Focus
    - Primary_Actor_Type
    - Geographic_Scope
    - Relationship_Model_Definition
    - Discourse_Type
features:
  frame_analysis:
    enable: false
    frame_threshold: 0.1
  source_comparison:
    enable: true
    source_column: Source
  time_evolution:
    date_column: 日期
    enable: true
    time_periods: 10
output_settings:
  folder: results
  names:
    analysis_report: 主题分析报告.txt
    document_mapping: 文档主题分布表.csv
    keyword_table: 主题关键词表.csv
    topic_summary: 主题摘要表.csv
outputs:
  analysis_report: true
  document_mapping: true
  interactive_charts: true
  keyword_table: true
  topic_summary: true
topic:
  advanced:
    keyword_extraction: standard
    min_dist: 0.0
    ngram_range:
    - 1
    - 3
  expected_topics: auto
  min_documents_per_topic: 15
  text_language: russian
