analysis:
  frame_analysis:
    enable: true
    threshold: 0.1
  source_analysis:
    enable: true
    source_column: Source
  time_analysis:
    bins: 10
    enable: true
    time_column: 日期
bertopic_params:
  embedding_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
  expert_keyword_extraction:
    custom_stopwords_path: stopwords/politics_stopwords.txt
    enable_multilingual_preprocessing: true
    enable_pos_patterns: true
    pos_language_detection: true
    pos_patterns:
      en: <JJ.*>*<NN.*>+
      ru: <A.*>*<N.*>+
      zh: <n.*|a.*>*<n.*>+
    use_custom_stopwords: true
  hdbscan_params:
    cluster_selection_method: eom
    metric: euclidean
    min_cluster_size: 15
    min_samples: 5
    prediction_data: true
  language: multilingual
  min_topic_size: 15
  n_gram_range:
  - 1
  - 3
  nr_topics: auto
  umap_params:
    metric: cosine
    min_dist: 0.0
    n_components: 5
    n_neighbors: 15
    random_state: 42
data_paths:
  media_data: data/媒体_最终分析数据库.xlsx
  social_media_data: data/社交媒体_最终分析数据库.xlsx
data_processing:
  merge_strategy: concat
  metadata_columns:
  - 序号
  - 日期
  - 标题
  - 链接
  - Token数
  - text
  - token数
  - Unit_ID
  - Source
  - Macro_Chunk_ID
  - speaker
  - Unit_Text
  - seed_sentence
  - expansion_logic
  - Unit_Hash
  - processing_status
  - Incident
  - Valence
  - Frame_ProblemDefinition
  - Frame_ProblemDefinition_Present
  - Frame_ResponsibilityAttribution
  - Frame_ResponsibilityAttribution_Present
  - Frame_MoralEvaluation
  - Frame_MoralEvaluation_Present
  - Frame_SolutionRecommendation
  - Frame_TreatmentRecommendation_Present
  - Frame_ActionStatement
  - Frame_ConflictAttribution_Present
  - Frame_CausalExplanation
  - Frame_CausalInterpretation_Present
  - Evidence_Type
  - Attribution_Level
  - Temporal_Focus
  - Primary_Actor_Type
  - Geographic_Scope
  - Relationship_Model_Definition
  - Discourse_Type
  text_column: Unit_Text
hyperparameter_optimization:
  auto_apply_best: false
  coherence_type: c_v
  enable: false
  n_trials: 100
  save_intermediate: true
  save_top_n: 5
  search_space:
    max_features:
    - 1000
    - 10000
    min_cluster_size:
    - 5
    - 100
    min_dist:
    - 0.0
    - 0.5
    min_samples:
    - 1
    - 15
    n_components:
    - 2
    - 10
    n_neighbors:
    - 5
    - 50
    ngram_range:
    - 1
    - 4
  show_progress: true
  study_name: auto
results_paths:
  cross_lingual_file: results/cross_lingual_composition.csv
  evolution_file: results/dynamic_evolution_analysis.csv
  frame_heatmap: results/topic_frame_heatmap.html
  model_dir: results/trained_model
  output_dir: results
  source_analysis: results/topic_by_source.html
  summary_enhanced: results/topics_summary_enhanced.csv
  summary_file: results/topics_summary.csv
  timeline_analysis: results/topics_over_time.html
  viz_file: results/topic_visualization.html
system:
  random_seed: 42
  save_intermediate: false
  use_gpu: false
  verbose: true
visualization:
  color_scheme: viridis
  dpi: 300
  figsize:
  - 12
  - 8
  save_format: png
  sota_charts:
    annotation_examples: []
    color_palette: academic
    enable: true
    enable_annotations: true
    font_family: Arial
    formats:
    - png
    - svg
    high_dpi: 300
  style: matplotlib
